### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by ToughGuyKunio** [Swordfish90/Lemuroid#48] opened 2020-02-26 16:08 UTC
Can you publish this on the FOSS [F-droid](https://f-droid.org/) store?

**Comment by Swordfish90** [comment] 2020-02-29 07:09
Hi @ToughGuyKunio, this is still something that I need to investigate because Lemuroid downloads precomiled cores from libretro buildbot. I'm marking this issue as duplicate of #3, you can find a bit more detail there.

**Closed by Swordfish90** 2020-02-29 07:09 UTC
Labels: duplicate
