### ISSUE TITLE
Turn off automatic scraping

### ISSUE THREAD

**Issue by arnoldsecret** [Swordfish90/Lemuroid#40] opened 2020-01-29 23:24 UTC
This feature bloats the storage since the scraper usually scrapes images in the highest quality possible.

**Comment by Amnesia1000** [comment] 2020-01-30 15:12
The use of disk space is minimal, I think it should be enabled by default, but with the possibility of deactivating it from options.

**Comment by Swordfish90** [comment] 2020-01-31 23:21
I think we should separate the issue from the suggested solution.

Lemuroid already supports Android Scoped Storage (which will be mandatory quite soon), so cores cannot directly access ROMs files, and need to be copied temporarily in a cache directory.
Currently there is no auto-cleanup, so those files pile up until you manually clean them.

This is probably the cause of storage bloat you see and will be fixed in the next few days with a task which clears up the oldest files.

**Comment by Swordfish90** [comment] 2020-02-01 11:49
Cache usage is now limited to 1/20th of internal device storage 3a3a57c95eb0a7cfe30dbd8d9f77e0d0565c8dca . This parameter is currently hardcoded and I might consider to expose it to the user in the future.

**Closed by Swordfish90** 2020-02-01 11:49 UTC
