### ISSUE TITLE
On screen controller not working

### ISSUE THREAD

**Issue by sam-gilroy** [Swordfish90/Lemuroid#197] opened 2021-03-07 03:44 UTC
The virtual buttons arent working as of the new update (1.9.1). In DS games the touch screen is fine but trying to push any buttons does nothing. I can occassionally get the settings menu to open by pressing a spot above the X button but below the DS touch screen. This was not happening on the previous version

Device: Samsung Galaxy S20FE
OS: Android 11

**Comment by Swordfish90** [comment] 2021-03-07 10:25
Hi @sam-gilroy. I'm afraid I'm aware of touch-screen issues on Samsung devices running Android 11. The only workaround is currently disabling Game Mode for Lemuroid, or setting the resolution scaling to 100%.

I'm closing the issue as a duplicate of #178 . Feel free to add there if the workaround doesn't work for you or you have more insight on the matter.

**Closed by Swordfish90** 2021-03-07 10:25 UTC
