### ISSUE TITLE
fingerprint scanner shown as controller (uinput-ftp)

### ISSUE THREAD

**Issue by Poru86** [Swordfish90/Lemuroid#238] opened 2021-04-20 21:43 UTC
The fingerprint scanner is shown as a controller so when i use my controller it ends up as a secondary controller and doesent leave me controll anything (my phone is a samsung A20s with android Q) hope you can fix it.

**Comment by Swordfish90** [comment] 2021-04-28 09:19
This is a duplicate of #215 which has been taken care off. From the next release, you'll be able to disable the fingerprint scanner so it will no longer take the gamepad role.

**Closed by Swordfish90** 2021-04-28 09:19 UTC
