### ISSUE TITLE
Bug with 1.8.0

### ISSUE THREAD

**Issue by YourHerbyWaifuCollector** [Swordfish90/Lemuroid#153] opened 2020-12-27 09:01 UTC
![Screenshot_2020-12-27-16-59-42-190_com swordfish lemuroid](https://user-images.githubusercontent.com/74519448/103167289-f4726800-4864-11eb-8758-644e562eed5d.jpg)
![Screenshot_2020-12-27-16-59-23-302_com swordfish lemuroid](https://user-images.githubusercontent.com/74519448/103167291-f63c2b80-4864-11eb-822e-0a252ced226b.jpg)
![Screenshot_2020-12-27-16-59-35-409_com swordfish lemuroid](https://user-images.githubusercontent.com/74519448/103167292-f6d4c200-4864-11eb-9b11-5a4866e34bbe.jpg)
![Screenshot_2020-12-27-16-59-31-469_com swordfish lemuroid](https://user-images.githubusercontent.com/74519448/103167293-f76d5880-4864-11eb-82b4-1534fba1719e.jpg)

lemuroid
lemuroid-app-free-release

**Comment by Swordfish90** [comment] 2020-12-29 10:12
Hi. Thank you for reporting it, but this is actually a duplicate of https://github.com/Swordfish90/Lemuroid/issues/149 .

**Closed by Swordfish90** 2020-12-29 10:12 UTC
