### ISSUE TITLE
PIXEL Mode

### ISSUE THREAD

**Issue by ghost** [Swordfish90/Lemuroid#460] opened 2022-06-12 22:52 UTC
Is it possible to add PIXEL Mode (Normal 4x)
It Means Non-Linear and shows Pixelated. For example: NES/FC Games on LCD TV / Monitor

**Comment by airon90** [comment] 2022-07-11 09:22
I suppose it is a duplicate of #473

**Closed** 2022-07-17 16:15 UTC
