### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by rodrigoswz** [Swordfish90/Lemuroid#51] opened 2020-03-01 16:26 UTC
I have a Xiaomi Mi Box with several emulators, I would like to replace everyone with Lemuroid but unfortunately this is not supported.

As an attempt at a temporary solution, I tried to install APK manually, obviously it installs but I can't select the game folder without Lemuroid closes immediately.

A proper Android TV UI would also be great, but just making it work would make me happy :)

**Comment by Swordfish90** [comment] 2020-03-01 20:32
Hi! I think your TV box doesn't support Android Storage Framework and that's why you are not seeing the folder picker. There is a workaround to this: you can copy your ROM files into an internal Lemuroid directory located at: _/Android/data/com.swordfish.lemuroid/files/roms_. These files will be picked up at the next rescan.

Let me know if that works for you.

I'm sure a proper Android TV UI will come with time.

**Comment by Swordfish90** [comment] 2020-03-28 11:32
I just finished implementing the Leanback version of Lemuroid. Would you mind giving it a spin on your Mi Box to see how it behaves?

I'm not expecting 3D consoles to work (they are not on my Firestick 4k), but for 2D gaming it should be fine. 

https://github.com/Swordfish90/Lemuroid/releases/tag/1.2.0-rc1

**Comment by rodrigoswz** [comment] 2020-03-28 15:43
When I installed it on my Mi Box I still had the phone UI and I couldn't select a ROM directory, I decided to manually try to grant storage permission in the app info and the Leanback UI appeared!

I was able to select the directory and play my games, thank you very much!

I think the only "bug" really is Lemuroid not asking for storage permission once it’s opened for the first time :)

A question: Will this version be able to be installed directly from Google Play on my Mi Box?

**Comment by Swordfish90** [comment] 2020-03-28 23:20
Thank you! I just needed some testing with the new OpenGLES 2 renderer and if you can play games I guess it's working.

I'll take a look at the permissions issues.

> A question: Will this version be able to be installed directly from Google Play on my Mi Box?
Yes, this is a debug build, I will push an updated version on Google Play in the next days.

**Comment by rodrigoswz** [comment] 2020-04-01 03:25
Hi again Filippo, today I received the beta update through Google Play. Thank you! But I had to sideload it because Google Play on my Mi Box says that Lemuroid it's incompatible.

In addition, strangely no game is opening, there is the opening animation, the screen flashes quickly and returns to the game list. The Storage permission was also not automatically requested.

**Comment by Swordfish90** [comment] 2020-04-01 17:18
Thank you for beta testing it thoroughly.

There is surely an issue with the current configuration on Google Play because it looks like Lemuroid is not supported on any TV (I'll take a look at this as soon as possible).

So it was working on the debug build but it broke on the release build you are using now? Sadly I'm not able to reproduce those issues (permissions and crash) on my Firestick or on the emulator.

Are you able to provide the stacktrace of your crash by using Logcat on your MiBox? Also, which Android version are you running on it?

**Comment by rodrigoswz** [comment] 2020-04-02 15:02
Exactly, in debug it worked perfectly, not in beta.

I tried a logcat but unfortunately there are some problems due to the fact that I use an external hard drive as an internal storage. When I turn on USB Debugging, it disables any USB, that is, I "lost" the internal storage to run a ROM or select a directory through Lemuroid.

My Android TV version is 8.0.0.

**Comment by Swordfish90** [comment] 2020-05-01 23:18
Sorry for the very long delay on this issue. I found a crash on play store which was linked to the missing permissions on tv and I fixed it, but I still have no idea what's wrong when the permissions are provided. Since you are able to reproduce it consistently, would you mind sending me an email so that I can give you a release apk which prints on screen what goes wrong?

**Comment by rodrigoswz** [comment] 2020-05-02 02:24
> Sorry for the very long delay on this issue. I found a crash on play store which was linked to the missing permissions on tv and I fixed it, but I still have no idea what's wrong when the permissions are provided. Since you are able to reproduce it consistently, would you mind sending me an email so that I can give you a release apk which prints on screen what goes wrong?

No problem! Email sent.

**Comment by smcue** [comment] 2020-05-07 21:15
Hi, if needed I'm available for testing too, I have a Mi Box and a Shield TV.

**Comment by Swordfish90** [comment] 2020-05-07 21:31
@smcue Thank you very much!... So the status of this feature is that the UI itself seems to be in place, but @rodrigoswz is having performance issues on the Mi Box. I guess it would be interesting to see how it behaves on the much more powerful Shield TV.

In the meantime I'm trying to get the approval to publish it on PlayStore as a TV app.

**Comment by Tossis** [comment] 2020-05-10 17:11
I've ordered a 2019 shield TV. Will leave a comment when I tested

**Comment by smcue** [comment] 2020-05-10 22:56
> @smcue Thank you very much!... So the status of this feature is that the UI itself seems to be in place, but @rodrigoswz is having performance issues on the Mi Box. I guess it would be interesting to see how it behaves on the much more powerful Shield TV.

Don't doubt the Shield having any issues, as for the Mi Box it's a different story, however it does seem to run RetroArch fine.
I have a similar setup as @rodrigoswz, could you maybe send me the test apk, so I can confirm? thanks

> In the meantime I'm trying to get the approval to publish it on PlayStore as a TV app.

Ah, it's great to see the project progressing well!

**Comment by s0ulst3aler** [comment] 2020-05-13 03:07
hi! i installed the app on TCL P8M with Android TV qnd its fine. the app find my roms, but my gamepad bluetooth doesnt work inside game

**Comment by Swordfish90** [comment] 2020-05-13 17:29
@smcue Thanks, I just uploaded a release apk of the latest tagged version: https://github.com/Swordfish90/Lemuroid/releases/tag/1.4.0

Hi @s0ulst3aler, which gamepad are you using? If you go to Settings -> Gamepad settings, do you see your gamepad controls?

**Comment by s0ulst3aler** [comment] 2020-05-13 17:33
@Swordfish90  i'm using 8 bit do nes30 pro, in settings this works fine, but inside game no

**Comment by rodrigoswz** [comment] 2020-05-13 17:55
Unfortunately the problem of slowness in the game still happens to me in version 1.4.0. If possible @smcue test it on your MiBox and give us feedback.

**Comment by smcue** [comment] 2020-05-14 00:38
> @smcue Thanks, I just uploaded a release apk of the latest tagged version: https://github.com/Swordfish90/Lemuroid/releases/tag/1.4.0
> 
Just tested this release, and I have the same issue @rodrigoswz initially had, where 'Android Storage Framework' was not supported, however using the workaround, by manually allowing 'Storage' permission via ATV Settings, the Leanback UI appeared, which allowed me to scan for ROM directories.

It seems the runtime permission is still not being prompted upon app launch.

Regarding performance issues, I wasn't really able to test more intensive games as the only ROMs that were playable were SNES and GBA.

Amiga, Dreamcast, PSX ROMs were not detected, as for N64, Lemuroid refused to play them, throwing a incompatibility message, despite being able to run it on mobile, and other emulators.

**Comment by Tossis** [comment] 2020-05-15 08:38
Tested on my ShieldTV (2019) - not the PRO model, the regular one - with my 8bitDo SF30Pro controller. NES, SNES, GBA, GB(C), N64 work as expected. Don't have any PSP or PSX to test.

**Comment by Swordfish90** [comment] 2020-05-16 10:11
@smcue were you seeing the Android TV interface or just the standard mobile one? Also, @rodrigoswz was seeing performance problems on basically any game, so I guess that's good news.

N64 are not supposed to work since an OpenGLES3 device is required for 3D in Lemuroid (and frankly it won't work very well; I'm not able to play on my FireStick 4k which has a slightly better gpu).

@Tossis perfect, thanks you very much.

I'm going to close this issue, since the TV implementation is complete and accepted by the PlayStore and open as separate issues regarding the problems you guys found.

**Closed by Swordfish90** 2020-05-16 10:11 UTC
