### ISSUE TITLE
Touch screen not aligned with buttons

### ISSUE THREAD

**Issue by BHydden** [Swordfish90/Lemuroid#476] opened 2022-07-03 08:47 UTC
**Disclamer**
In order to keep this bug tracker manageable, you need to keep a few things in mind:
* Any issue not following this template will be closed as invalid
* Is the issue reproducible on RetroArch with the same core? If so, it's very likely a core issue and the upstream core repository is a better place to file it
* Is the issue already opened? Try out a search before filing one.

**Describe the bug**
Many times, but not always, my touchscreen is not aligned with the controller buttons. Sometimes a restart corrects this but not always. This behaviour is only in this app, all other apps work fine.

**To Reproduce**
1. Go to gba emulator
2. See that buttons don't work as expected.

**Expected behavior**
Buttons to be aligned with their touch point

**Screenshots**
Can't really screen shot where I'm touching my phone.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A13 (SM-A135F)
 - OS: Android 12 One UI 4.1
 - Browser Lemuroid (from F-droid)
 - Version 1.13.3 (recommended)

**Additional context**
Couldn't find any related open issues.

**Comment by BHydden** [comment] 2022-07-03 08:50
I don't think it's relevant but the rom is pokemon fire red, though I don't think the rom would break button location?

**Comment by BHydden** [comment] 2022-07-04 21:37
Factory reset didn't change anything. 

Uninstalling and reinstalling the app seemed to resolve it at the cost of my save file, but 2 days later the problem returned. Any ideas on further tests or remedies I can try?

**Comment by Swordfish90** [comment] 2022-07-17 16:11
Hi @BHydden . This issue is a duplicate of #178 . It's an issue caused by Samsung own Game Mode and they are the only one that can fix it. You can find some useful workarounds linked in the other issue.

**Closed by Swordfish90** 2022-07-17 16:11 UTC
