### ISSUE TITLE
PSX Controls Aren't Working Well on Tablet

### ISSUE THREAD

**Issue by RomuloCF** [Swordfish90/Lemuroid#309] opened 2021-08-30 17:05 UTC
Hello!

PSX controls aren't working well on my tablet. These are the issues:

- Left pads (Directionals, L1 and L2) are unsynchronized: The place I need to touch to press is above the place where the pad is.
- Right pads (triangle, square, circle, x) only work if I'm pressing the directionals.

The setting button is the only one that works well, and I already tried to edit the control and change it to Dualshock, remain the issues.
 
My tablet is a Galaxy Tab A with S pen (SM-P205) and it use the Android 11.

Could you help me to fix it?

Thanks.

**Comment by Wifimuffin** [comment] 2021-09-03 01:28
I’m having the exact same problem with the DS and GBA emulators on the Galaxy S20 FE. Perhaps it’s a problem with Samsung devices?

**Comment by hhromic** [comment] 2021-09-03 18:44
This is a known issue. I have faced it myself as well.
This workaround worked for me: https://github.com/Swordfish90/Lemuroid/issues/178#issuecomment-785145153

**Comment by RomuloCF** [comment] 2021-09-03 21:15
Hello, thanks for your help. I already tried this workaround, but I discovered I don't have any Samsung game booster apps on my Tablet. They aren't compatible with it. And I haven't any other similar app, so I'm not sure what I should do to fix this issue in my case.

**Comment by Wifimuffin** [comment] 2021-09-03 21:31
> Hello, thanks for your help. I already tried this workaround, but I discovered I haven't any Samsung game booster apps on my Tablet. They aren't compatible with it, and I haven't any other similar app, so I'm not sure what I should do to fix this issue in my case.

Here’s what I did to get it working for me:

Install both Game plugins and Game booster plus from the Galaxy store

Open plugin

Unlike page above, default should be at 100. Set to 75 and move Slider from “Maximum” to “Balanced”

This worked for me, let me know if it works for you.

**Comment by RomuloCF** [comment] 2021-09-03 21:58
> > Hello, thanks for your help. I already tried this workaround, but I discovered I haven't any Samsung game booster apps on my Tablet. They aren't compatible with it, and I haven't any other similar app, so I'm not sure what I should do to fix this issue in my case.
> 
> Here’s what I did to get it working for me:
> 
> Install both Game plugins and Game booster plus from the Galaxy store
> 
> Open plugin
> 
> Unlike page above, default should be at 100. Set to 75 and move Slider from “Maximum” to “Balanced”
> 
> This worked for me, let me know if it works for you.

**Comment by RomuloCF** [comment] 2021-09-03 22:00
Thanks for the tip, but I couldn't install this app because it isn't available for my device. It doesn't even appear on Galaxy Store or another place. I just tried installing another similar app and changing the settings, but it doesn't work.

**Comment by Wifimuffin** [comment] 2021-09-03 22:34
> Thanks for the tip, but I couldn't install this app because it isn't available for my device. It doesn't even appear on Galaxy Store or another place. I just tried installing another game booster app and changing the settings, but it didn't work.

Ah, I can’t help you then, sorry. Hopefully someone will come up with a real solution!

**Comment by Swordfish90** [comment] 2021-11-23 17:36
This is actually a duplicate of https://github.com/Swordfish90/Lemuroid/issues/178 . Let's keep it in the original thread.

**Closed by Swordfish90** 2021-11-23 17:36 UTC
Labels: duplicate
