### ISSUE TITLE
Controlls are offeset

### ISSUE THREAD

**Issue by wallop560** [Swordfish90/Lemuroid#432] opened 2022-05-11 09:32 UTC
When I open the app the controlls are all offset upwards. I saw some posts on reddit with the same issue but the workarounds didn't work for my phone (samsung a13, android 12)

**Comment by okletsgobaby** [comment] 2022-05-26 10:39
yeah me too. I assume this problem is specific to exynos chipset. Im using galaxy a50s. And i also try it on my friends phone Galaxy A6+ with Snapdragon Chipsets and its working fine.

**Comment by Swordfish90** [comment] 2022-07-17 16:23
This is is a duplicate of #178 . It's an issue caused by Samsung Game Mode which tampers with touch controls and they are the only one that can fix it. You can find some workarounds at the link I provided.

**Closed by Swordfish90** 2022-07-17 16:23 UTC
