### ISSUE TITLE
Touch control issue 

### ISSUE THREAD

**Issue by fankewong** [Swordfish90/Lemuroid#481] opened 2022-07-14 06:52 UTC
Cannot use touch control correctly.
Single touch on left or right area's button, no response.
When touch and hold on the left area button, then the right area touch works.
Either when touch and hold on the right area button, then the left area touch works.

App version 1.14
My Android version 12
CPU: Mediatek dimensity 1200

But, it has NO issue running on my another Android
Android version 11
CPU: Snapdragon S840

**Comment by Swordfish90** [comment] 2022-07-17 16:06
This is a duplicate of #178 . Sadly this is an issue on Samsung device that tamper with touch coordinates. I already tried and there is nothing I can do, you need to get in touch with Samsung and report the issue to them.

**Closed by Swordfish90** 2022-07-17 16:06 UTC
